<?php
/**
 * @file
 * campaign_related.features.node_export_features.inc
 */

/**
 * Implements hook_node_export_features_default().
 */
function campaign_related_node_export_features_default() {
  $node_export = array(
  'code_string' => 'array(
  (object) array(
      \'body\' => array(
        \'und\' => array(
          array(
            \'value\' => \'To lead a united, informed and prosperous constituency, to peacefully and democratically cultivate the spirit of self reliance among my people, by advocating against factors that bring underdevelopment\',
            \'summary\' => \'\',
            \'format\' => \'html\',
            \'safe_value\' => \'To lead a united, informed and prosperous constituency, to peacefully and democratically cultivate the spirit of self reliance among my people, by advocating against factors that bring underdevelopment\',
            \'safe_summary\' => \'\',
          ),
        ),
      ),
      \'changed\' => NULL,
      \'cid\' => \'0\',
      \'comment\' => \'2\',
      \'comment_count\' => \'0\',
      \'created\' => NULL,
      \'data\' => \'a:1:{s:7:"overlay";i:1;}\',
      \'field_account_name\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Adakole Oko Daniel\',
            \'format\' => NULL,
            \'safe_value\' => \'Adakole Oko Daniel\',
          ),
        ),
      ),
      \'field_account_number\' => array(
        \'und\' => array(
          array(
            \'value\' => \'0002152518\',
            \'format\' => NULL,
            \'safe_value\' => \'0002152518\',
          ),
        ),
      ),
      \'field_bank_name\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Access Bank\',
            \'format\' => NULL,
            \'safe_value\' => \'Access Bank\',
          ),
        ),
      ),
      \'field_date_of_birth\' => array(
        \'und\' => array(
          array(
            \'value\' => \'1981-09-03 00:00:00\',
            \'timezone\' => \'Africa/Lagos\',
            \'timezone_db\' => \'Africa/Lagos\',
            \'date_type\' => \'datetime\',
          ),
        ),
      ),
      \'field_education\' => array(
        \'und\' => array(
          array(
            \'value\' => \'20\',
            \'revision_id\' => \'20\',
          ),
          array(
            \'value\' => \'21\',
            \'revision_id\' => \'21\',
          ),
        ),
      ),
      \'field_email\' => array(
        \'und\' => array(
          array(
            \'email\' => \'danyadakole@gmail.com\',
          ),
        ),
      ),
      \'field_facebook_page\' => array(),
      \'field_first_name\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Daniel\',
            \'format\' => NULL,
            \'safe_value\' => \'Daniel\',
          ),
        ),
      ),
      \'field_instagram_handle\' => array(),
      \'field_last_name\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Adakole\',
            \'format\' => NULL,
            \'safe_value\' => \'Adakole\',
          ),
        ),
      ),
      \'field_linkedin_page\' => array(),
      \'field_manifesto\' => array(),
      \'field_middle_name\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Oko\',
            \'format\' => NULL,
            \'safe_value\' => \'Oko\',
          ),
        ),
      ),
      \'field_personal_title\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Mr\',
          ),
        ),
      ),
      \'field_phone\' => array(
        \'und\' => array(
          array(
            \'value\' => \'08130623056\',
            \'format\' => NULL,
            \'safe_value\' => \'08130623056\',
          ),
        ),
      ),
      \'field_political_party\' => array(
        \'und\' => array(
          array(
            \'tid\' => \'2924\',
          ),
        ),
      ),
      \'field_position_running_for\' => array(
        \'und\' => array(
          array(
            \'tid\' => \'1847\',
          ),
        ),
      ),
      \'field_profile_image\' => array(
        \'und\' => array(
          array(
            \'fid\' => \'92\',
            \'uid\' => \'1\',
            \'filename\' => \'campaign pix s.jpg\',
            \'uri\' => \'public://campaign pix s_0.jpg\',
            \'filemime\' => \'image/jpeg\',
            \'filesize\' => \'52131\',
            \'status\' => \'1\',
            \'timestamp\' => \'1529939177\',
            \'type\' => \'image\',
            \'uuid\' => \'922e78d5-40ef-4706-9b79-607ae8339470\',
            \'field_file_image_alt_text\' => array(),
            \'field_file_image_title_text\' => array(),
            \'rdf_mapping\' => array(),
            \'metadata\' => array(
              \'height\' => 1050,
              \'width\' => 750,
            ),
            \'height\' => \'1050\',
            \'width\' => \'750\',
            \'alt\' => \'\',
            \'title\' => \'\',
          ),
        ),
      ),
      \'field_resume_cv\' => array(),
      \'field_twitter_handle\' => array(),
      \'field_website\' => array(),
      \'files\' => array(),
      \'language\' => \'und\',
      \'last_comment_name\' => NULL,
      \'last_comment_timestamp\' => NULL,
      \'last_comment_uid\' => \'1\',
      \'log\' => \'\',
      \'menu\' => NULL,
      \'name\' => \'campaign\',
      \'nid\' => NULL,
      \'node_export_drupal_version\' => \'7\',
      \'path\' => NULL,
      \'picture\' => \'0\',
      \'promote\' => \'0\',
      \'rdf_mapping\' => array(
        \'rdftype\' => array(
          \'sioc:Item\',
          \'foaf:Document\',
        ),
        \'title\' => array(
          \'predicates\' => array(
            \'dc:title\',
          ),
        ),
        \'created\' => array(
          \'predicates\' => array(
            \'dc:date\',
            \'dc:created\',
          ),
          \'datatype\' => \'xsd:dateTime\',
          \'callback\' => \'date_iso8601\',
        ),
        \'changed\' => array(
          \'predicates\' => array(
            \'dc:modified\',
          ),
          \'datatype\' => \'xsd:dateTime\',
          \'callback\' => \'date_iso8601\',
        ),
        \'body\' => array(
          \'predicates\' => array(
            \'content:encoded\',
          ),
        ),
        \'uid\' => array(
          \'predicates\' => array(
            \'sioc:has_creator\',
          ),
          \'type\' => \'rel\',
        ),
        \'name\' => array(
          \'predicates\' => array(
            \'foaf:name\',
          ),
        ),
        \'comment_count\' => array(
          \'predicates\' => array(
            \'sioc:num_replies\',
          ),
          \'datatype\' => \'xsd:integer\',
        ),
        \'last_activity\' => array(
          \'predicates\' => array(
            \'sioc:last_activity_date\',
          ),
          \'datatype\' => \'xsd:dateTime\',
          \'callback\' => \'date_iso8601\',
        ),
      ),
      \'revision_timestamp\' => NULL,
      \'revision_uid\' => \'1\',
      \'status\' => \'0\',
      \'sticky\' => \'0\',
      \'title\' => \'Mr Daniel Adakole for Otukpo, Benue, House of Assembly\',
      \'tnid\' => \'0\',
      \'translate\' => \'0\',
      \'type\' => \'campaign\',
      \'uid\' => \'1\',
      \'uuid\' => \'08eb7ffd-3dfe-4133-8918-4b1c0a525b0c\',
      \'vid\' => NULL,
      \'vuuid\' => \'7dab8bd1-e11b-4c4e-83c3-02f7e75f2037\',
    ),
  (object) array(
      \'body\' => array(
        \'und\' => array(
          array(
            \'value\' => \'The legislative arm of government based on my experience suits my set of skills and there is a need to up the ante on the available bills made in the house\',
            \'summary\' => \'\',
            \'format\' => \'html\',
            \'safe_value\' => \'The legislative arm of government based on my experience suits my set of skills and there is a need to up the ante on the available bills made in the house\',
            \'safe_summary\' => \'\',
          ),
        ),
      ),
      \'changed\' => NULL,
      \'cid\' => \'0\',
      \'comment\' => \'2\',
      \'comment_count\' => \'0\',
      \'created\' => NULL,
      \'data\' => \'a:1:{s:7:"overlay";i:1;}\',
      \'field_account_name\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Kunle Lawal campaign account\',
            \'format\' => NULL,
            \'safe_value\' => \'Kunle Lawal campaign account\',
          ),
        ),
      ),
      \'field_account_number\' => array(
        \'und\' => array(
          array(
            \'value\' => \'1005839530\',
            \'format\' => NULL,
            \'safe_value\' => \'1005839530\',
          ),
        ),
      ),
      \'field_bank_name\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Zenith Bank\',
            \'format\' => NULL,
            \'safe_value\' => \'Zenith Bank\',
          ),
        ),
      ),
      \'field_date_of_birth\' => array(
        \'und\' => array(
          array(
            \'value\' => \'1978-12-28 00:00:00\',
            \'timezone\' => \'Africa/Lagos\',
            \'timezone_db\' => \'Africa/Lagos\',
            \'date_type\' => \'datetime\',
          ),
        ),
      ),
      \'field_education\' => array(
        \'und\' => array(
          array(
            \'value\' => \'25\',
            \'revision_id\' => \'25\',
          ),
        ),
      ),
      \'field_email\' => array(),
      \'field_facebook_page\' => array(
        \'und\' => array(
          array(
            \'value\' => \'www.facebook.com/kunle.lawal\',
            \'format\' => NULL,
            \'safe_value\' => \'www.facebook.com/kunle.lawal\',
          ),
        ),
      ),
      \'field_first_name\' => array(
        \'und\' => array(
          array(
            \'value\' => \'KUNLE\',
            \'format\' => NULL,
            \'safe_value\' => \'KUNLE\',
          ),
        ),
      ),
      \'field_instagram_handle\' => array(
        \'und\' => array(
          array(
            \'value\' => \'@kunlelawal2019\',
            \'format\' => NULL,
            \'safe_value\' => \'@kunlelawal2019\',
          ),
        ),
      ),
      \'field_last_name\' => array(
        \'und\' => array(
          array(
            \'value\' => \'LAWAL\',
            \'format\' => NULL,
            \'safe_value\' => \'LAWAL\',
          ),
        ),
      ),
      \'field_linkedin_page\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Kunle Lawal\',
            \'format\' => NULL,
            \'safe_value\' => \'Kunle Lawal\',
          ),
        ),
      ),
      \'field_manifesto\' => array(),
      \'field_middle_name\' => array(
        \'und\' => array(
          array(
            \'value\' => \'IBRAHIM\',
            \'format\' => NULL,
            \'safe_value\' => \'IBRAHIM\',
          ),
        ),
      ),
      \'field_personal_title\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Mr\',
          ),
        ),
      ),
      \'field_phone\' => array(
        \'und\' => array(
          array(
            \'value\' => \'08097759999\',
            \'format\' => NULL,
            \'safe_value\' => \'08097759999\',
          ),
        ),
      ),
      \'field_political_party\' => array(
        \'und\' => array(
          array(
            \'tid\' => \'2902\',
          ),
        ),
      ),
      \'field_position_running_for\' => array(
        \'und\' => array(
          array(
            \'tid\' => \'1256\',
          ),
        ),
      ),
      \'field_profile_image\' => array(
        \'und\' => array(
          array(
            \'fid\' => \'94\',
            \'uid\' => \'1\',
            \'filename\' => \'image1.jpeg\',
            \'uri\' => \'public://image1_0.jpeg\',
            \'filemime\' => \'image/jpeg\',
            \'filesize\' => \'89606\',
            \'status\' => \'1\',
            \'timestamp\' => \'1529940598\',
            \'type\' => \'image\',
            \'uuid\' => \'7439bb28-5682-4ed4-9796-33b157b8cb4b\',
            \'field_file_image_alt_text\' => array(),
            \'field_file_image_title_text\' => array(),
            \'rdf_mapping\' => array(),
            \'metadata\' => array(
              \'height\' => 1080,
              \'width\' => 910,
            ),
            \'height\' => \'1080\',
            \'width\' => \'910\',
            \'alt\' => \'\',
            \'title\' => \'\',
          ),
        ),
      ),
      \'field_resume_cv\' => array(
        \'und\' => array(
          array(
            \'fid\' => \'95\',
            \'uid\' => \'1\',
            \'filename\' => \'Adekunle Ibrahim Lawal CV.pdf\',
            \'uri\' => \'public://Adekunle Ibrahim Lawal CV.pdf\',
            \'filemime\' => \'application/pdf\',
            \'filesize\' => \'159645\',
            \'status\' => \'1\',
            \'timestamp\' => \'1529940598\',
            \'type\' => \'document\',
            \'uuid\' => \'ab000f8b-cbac-4711-b518-f39910462e97\',
            \'rdf_mapping\' => array(),
            \'metadata\' => array(),
            \'display\' => \'1\',
            \'description\' => \'\',
          ),
        ),
      ),
      \'field_twitter_handle\' => array(
        \'und\' => array(
          array(
            \'value\' => \'@kunlaylawal \',
            \'format\' => NULL,
            \'safe_value\' => \'@kunlaylawal \',
          ),
        ),
      ),
      \'field_website\' => array(),
      \'files\' => array(),
      \'language\' => \'und\',
      \'last_comment_name\' => NULL,
      \'last_comment_timestamp\' => NULL,
      \'last_comment_uid\' => \'1\',
      \'log\' => \'\',
      \'menu\' => NULL,
      \'name\' => \'campaign\',
      \'nid\' => NULL,
      \'node_export_drupal_version\' => \'7\',
      \'path\' => NULL,
      \'picture\' => \'0\',
      \'promote\' => \'0\',
      \'rdf_mapping\' => array(
        \'rdftype\' => array(
          \'sioc:Item\',
          \'foaf:Document\',
        ),
        \'title\' => array(
          \'predicates\' => array(
            \'dc:title\',
          ),
        ),
        \'created\' => array(
          \'predicates\' => array(
            \'dc:date\',
            \'dc:created\',
          ),
          \'datatype\' => \'xsd:dateTime\',
          \'callback\' => \'date_iso8601\',
        ),
        \'changed\' => array(
          \'predicates\' => array(
            \'dc:modified\',
          ),
          \'datatype\' => \'xsd:dateTime\',
          \'callback\' => \'date_iso8601\',
        ),
        \'body\' => array(
          \'predicates\' => array(
            \'content:encoded\',
          ),
        ),
        \'uid\' => array(
          \'predicates\' => array(
            \'sioc:has_creator\',
          ),
          \'type\' => \'rel\',
        ),
        \'name\' => array(
          \'predicates\' => array(
            \'foaf:name\',
          ),
        ),
        \'comment_count\' => array(
          \'predicates\' => array(
            \'sioc:num_replies\',
          ),
          \'datatype\' => \'xsd:integer\',
        ),
        \'last_activity\' => array(
          \'predicates\' => array(
            \'sioc:last_activity_date\',
          ),
          \'datatype\' => \'xsd:dateTime\',
          \'callback\' => \'date_iso8601\',
        ),
      ),
      \'revision_timestamp\' => NULL,
      \'revision_uid\' => \'1\',
      \'status\' => \'0\',
      \'sticky\' => \'0\',
      \'title\' => \'Mr KUNLE LAWAL for Federal Capital Territory, FCT, Senator\',
      \'tnid\' => \'0\',
      \'translate\' => \'0\',
      \'type\' => \'campaign\',
      \'uid\' => \'1\',
      \'uuid\' => \'55705ec4-b8e3-46af-86ab-744a8dd24041\',
      \'vid\' => NULL,
      \'vuuid\' => \'94fbea6f-89bc-41b8-b103-38da75413a2c\',
    ),
  (object) array(
      \'body\' => array(
        \'und\' => array(
          array(
            \'value\' => "<p>I’m running to inject progressive thinking and patriotism to governance. I’m running to ensure the basic necessities needed to live a decent and productive life are available to my constituents. I’m running to empower my people.</p>\\r\\n",
            \'summary\' => \'\',
            \'format\' => \'filtered_html\',
            \'safe_value\' => "<p>I’m running to inject progressive thinking and patriotism to governance. I’m running to ensure the basic necessities needed to live a decent and productive life are available to my constituents. I’m running to empower my people.</p>\\n",
            \'safe_summary\' => \'\',
          ),
        ),
      ),
      \'changed\' => NULL,
      \'cid\' => \'0\',
      \'comment\' => \'2\',
      \'comment_count\' => \'0\',
      \'created\' => NULL,
      \'data\' => \'a:1:{s:7:"overlay";i:1;}\',
      \'field_account_name\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Terseer Ugbor\',
            \'format\' => NULL,
            \'safe_value\' => \'Terseer Ugbor\',
          ),
        ),
      ),
      \'field_account_number\' => array(
        \'und\' => array(
          array(
            \'value\' => \'0080713619\',
            \'format\' => NULL,
            \'safe_value\' => \'0080713619\',
          ),
        ),
      ),
      \'field_bank_name\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Diamond bank\',
            \'format\' => NULL,
            \'safe_value\' => \'Diamond bank\',
          ),
        ),
      ),
      \'field_date_of_birth\' => array(
        \'und\' => array(
          array(
            \'value\' => \'1980-05-20 00:00:00\',
            \'timezone\' => \'Africa/Lagos\',
            \'timezone_db\' => \'Africa/Lagos\',
            \'date_type\' => \'datetime\',
          ),
        ),
      ),
      \'field_education\' => array(
        \'und\' => array(
          array(
            \'value\' => \'4\',
            \'revision_id\' => \'4\',
          ),
          array(
            \'value\' => \'5\',
            \'revision_id\' => \'5\',
          ),
          array(
            \'value\' => \'6\',
            \'revision_id\' => \'6\',
          ),
        ),
      ),
      \'field_email\' => array(
        \'und\' => array(
          array(
            \'email\' => \'terseerugbor@gmail.com\',
          ),
        ),
      ),
      \'field_facebook_page\' => array(
        \'und\' => array(
          array(
            \'value\' => \'facebook.com/terseer.ugbor\',
            \'format\' => NULL,
            \'safe_value\' => \'facebook.com/terseer.ugbor\',
          ),
        ),
      ),
      \'field_first_name\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Terseer\',
            \'format\' => NULL,
            \'safe_value\' => \'Terseer\',
          ),
        ),
      ),
      \'field_instagram_handle\' => array(),
      \'field_last_name\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Ugboor\',
            \'format\' => NULL,
            \'safe_value\' => \'Ugboor\',
          ),
        ),
      ),
      \'field_linkedin_page\' => array(),
      \'field_manifesto\' => array(),
      \'field_middle_name\' => array(),
      \'field_personal_title\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Mr\',
          ),
        ),
      ),
      \'field_phone\' => array(
        \'und\' => array(
          array(
            \'value\' => \'08033165162\',
            \'format\' => NULL,
            \'safe_value\' => \'08033165162\',
          ),
        ),
      ),
      \'field_political_party\' => array(
        \'und\' => array(
          array(
            \'tid\' => \'2886\',
          ),
        ),
      ),
      \'field_position_running_for\' => array(
        \'und\' => array(
          array(
            \'tid\' => \'1837\',
          ),
        ),
      ),
      \'field_profile_image\' => array(
        \'und\' => array(
          array(
            \'fid\' => \'86\',
            \'uid\' => \'1\',
            \'filename\' => \'ugbor.jpg\',
            \'uri\' => \'public://ugbor.jpg\',
            \'filemime\' => \'image/jpeg\',
            \'filesize\' => \'86043\',
            \'status\' => \'1\',
            \'timestamp\' => \'1529934938\',
            \'type\' => \'image\',
            \'uuid\' => \'b7a67aff-6f39-489d-845c-17edbf09869c\',
            \'field_file_image_alt_text\' => array(),
            \'field_file_image_title_text\' => array(),
            \'rdf_mapping\' => array(),
            \'metadata\' => array(
              \'height\' => 624,
              \'width\' => 446,
            ),
            \'height\' => \'624\',
            \'width\' => \'446\',
            \'alt\' => \'\',
            \'title\' => \'\',
          ),
        ),
      ),
      \'field_resume_cv\' => array(),
      \'field_twitter_handle\' => array(),
      \'field_website\' => array(),
      \'files\' => array(),
      \'language\' => \'und\',
      \'last_comment_name\' => NULL,
      \'last_comment_timestamp\' => NULL,
      \'last_comment_uid\' => \'1\',
      \'log\' => \'\',
      \'menu\' => NULL,
      \'name\' => \'campaign\',
      \'nid\' => NULL,
      \'node_export_drupal_version\' => \'7\',
      \'path\' => NULL,
      \'picture\' => \'0\',
      \'promote\' => \'0\',
      \'rdf_mapping\' => array(
        \'rdftype\' => array(
          \'sioc:Item\',
          \'foaf:Document\',
        ),
        \'title\' => array(
          \'predicates\' => array(
            \'dc:title\',
          ),
        ),
        \'created\' => array(
          \'predicates\' => array(
            \'dc:date\',
            \'dc:created\',
          ),
          \'datatype\' => \'xsd:dateTime\',
          \'callback\' => \'date_iso8601\',
        ),
        \'changed\' => array(
          \'predicates\' => array(
            \'dc:modified\',
          ),
          \'datatype\' => \'xsd:dateTime\',
          \'callback\' => \'date_iso8601\',
        ),
        \'body\' => array(
          \'predicates\' => array(
            \'content:encoded\',
          ),
        ),
        \'uid\' => array(
          \'predicates\' => array(
            \'sioc:has_creator\',
          ),
          \'type\' => \'rel\',
        ),
        \'name\' => array(
          \'predicates\' => array(
            \'foaf:name\',
          ),
        ),
        \'comment_count\' => array(
          \'predicates\' => array(
            \'sioc:num_replies\',
          ),
          \'datatype\' => \'xsd:integer\',
        ),
        \'last_activity\' => array(
          \'predicates\' => array(
            \'sioc:last_activity_date\',
          ),
          \'datatype\' => \'xsd:dateTime\',
          \'callback\' => \'date_iso8601\',
        ),
      ),
      \'revision_timestamp\' => NULL,
      \'revision_uid\' => \'1\',
      \'status\' => \'0\',
      \'sticky\' => \'0\',
      \'title\' => \'Mr Terseer Ugboor for Kwande East, Benue, House of Assembly\',
      \'tnid\' => \'0\',
      \'translate\' => \'0\',
      \'type\' => \'campaign\',
      \'uid\' => \'1\',
      \'uuid\' => \'5b13ec25-ef68-45b7-b520-9d5962092916\',
      \'vid\' => NULL,
      \'vuuid\' => \'52087d66-da8b-4a77-a6b8-3f90abbc7755\',
    ),
  (object) array(
      \'body\' => array(
        \'und\' => array(
          array(
            \'value\' => "<p><strong>To lead a united, informed and prosperous constituency, to peacefully and democratically cultivate the spirit of self reliance among my people, by advocating against factors that bring underdevelopment </strong></p>\\r\\n",
            \'summary\' => \'\',
            \'format\' => \'filtered_html\',
            \'safe_value\' => "<p><strong>To lead a united, informed and prosperous constituency, to peacefully and democratically cultivate the spirit of self reliance among my people, by advocating against factors that bring underdevelopment </strong></p>\\n",
            \'safe_summary\' => \'\',
          ),
        ),
      ),
      \'changed\' => NULL,
      \'cid\' => \'0\',
      \'comment\' => \'2\',
      \'comment_count\' => \'0\',
      \'created\' => NULL,
      \'data\' => \'a:1:{s:7:"overlay";i:1;}\',
      \'field_account_name\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Adakole Oko Daniel\',
            \'format\' => NULL,
            \'safe_value\' => \'Adakole Oko Daniel\',
          ),
        ),
      ),
      \'field_account_number\' => array(
        \'und\' => array(
          array(
            \'value\' => \'0002152518\',
            \'format\' => NULL,
            \'safe_value\' => \'0002152518\',
          ),
        ),
      ),
      \'field_bank_name\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Access Bank\',
            \'format\' => NULL,
            \'safe_value\' => \'Access Bank\',
          ),
        ),
      ),
      \'field_date_of_birth\' => array(
        \'und\' => array(
          array(
            \'value\' => \'1981-09-03 00:00:00\',
            \'timezone\' => \'Africa/Lagos\',
            \'timezone_db\' => \'Africa/Lagos\',
            \'date_type\' => \'datetime\',
          ),
        ),
      ),
      \'field_education\' => array(
        \'und\' => array(
          array(
            \'value\' => \'13\',
            \'revision_id\' => \'13\',
          ),
          array(
            \'value\' => \'14\',
            \'revision_id\' => \'14\',
          ),
        ),
      ),
      \'field_email\' => array(
        \'und\' => array(
          array(
            \'email\' => \'danyadakole@gmail.com\',
          ),
        ),
      ),
      \'field_facebook_page\' => array(),
      \'field_first_name\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Daniel\',
            \'format\' => NULL,
            \'safe_value\' => \'Daniel\',
          ),
        ),
      ),
      \'field_instagram_handle\' => array(),
      \'field_last_name\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Adakole\',
            \'format\' => NULL,
            \'safe_value\' => \'Adakole\',
          ),
        ),
      ),
      \'field_linkedin_page\' => array(),
      \'field_manifesto\' => array(),
      \'field_middle_name\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Oko\',
            \'format\' => NULL,
            \'safe_value\' => \'Oko\',
          ),
        ),
      ),
      \'field_personal_title\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Mr\',
          ),
        ),
      ),
      \'field_phone\' => array(
        \'und\' => array(
          array(
            \'value\' => \'08130623056\',
            \'format\' => NULL,
            \'safe_value\' => \'08130623056\',
          ),
        ),
      ),
      \'field_political_party\' => array(
        \'und\' => array(
          array(
            \'tid\' => \'2924\',
          ),
        ),
      ),
      \'field_position_running_for\' => array(
        \'und\' => array(
          array(
            \'tid\' => \'1847\',
          ),
        ),
      ),
      \'field_profile_image\' => array(
        \'und\' => array(
          array(
            \'fid\' => \'90\',
            \'uid\' => \'1\',
            \'filename\' => \'campaign pix s.jpg\',
            \'uri\' => \'public://campaign pix s.jpg\',
            \'filemime\' => \'image/jpeg\',
            \'filesize\' => \'52131\',
            \'status\' => \'1\',
            \'timestamp\' => \'1529937734\',
            \'type\' => \'image\',
            \'uuid\' => \'34ea6e27-51e1-4669-84a2-d27f0fdd8558\',
            \'field_file_image_alt_text\' => array(),
            \'field_file_image_title_text\' => array(),
            \'rdf_mapping\' => array(),
            \'metadata\' => array(
              \'height\' => 1050,
              \'width\' => 750,
            ),
            \'height\' => \'1050\',
            \'width\' => \'750\',
            \'alt\' => \'\',
            \'title\' => \'\',
          ),
        ),
      ),
      \'field_resume_cv\' => array(),
      \'field_twitter_handle\' => array(),
      \'field_website\' => array(),
      \'files\' => array(),
      \'language\' => \'und\',
      \'last_comment_name\' => NULL,
      \'last_comment_timestamp\' => NULL,
      \'last_comment_uid\' => \'1\',
      \'log\' => \'\',
      \'menu\' => NULL,
      \'name\' => \'campaign\',
      \'nid\' => NULL,
      \'node_export_drupal_version\' => \'7\',
      \'path\' => NULL,
      \'picture\' => \'0\',
      \'promote\' => \'0\',
      \'rdf_mapping\' => array(
        \'rdftype\' => array(
          \'sioc:Item\',
          \'foaf:Document\',
        ),
        \'title\' => array(
          \'predicates\' => array(
            \'dc:title\',
          ),
        ),
        \'created\' => array(
          \'predicates\' => array(
            \'dc:date\',
            \'dc:created\',
          ),
          \'datatype\' => \'xsd:dateTime\',
          \'callback\' => \'date_iso8601\',
        ),
        \'changed\' => array(
          \'predicates\' => array(
            \'dc:modified\',
          ),
          \'datatype\' => \'xsd:dateTime\',
          \'callback\' => \'date_iso8601\',
        ),
        \'body\' => array(
          \'predicates\' => array(
            \'content:encoded\',
          ),
        ),
        \'uid\' => array(
          \'predicates\' => array(
            \'sioc:has_creator\',
          ),
          \'type\' => \'rel\',
        ),
        \'name\' => array(
          \'predicates\' => array(
            \'foaf:name\',
          ),
        ),
        \'comment_count\' => array(
          \'predicates\' => array(
            \'sioc:num_replies\',
          ),
          \'datatype\' => \'xsd:integer\',
        ),
        \'last_activity\' => array(
          \'predicates\' => array(
            \'sioc:last_activity_date\',
          ),
          \'datatype\' => \'xsd:dateTime\',
          \'callback\' => \'date_iso8601\',
        ),
      ),
      \'revision_timestamp\' => NULL,
      \'revision_uid\' => \'1\',
      \'status\' => \'0\',
      \'sticky\' => \'0\',
      \'title\' => \'Mr Daniel Adakole for Otukpo, Benue, House of Assembly\',
      \'tnid\' => \'0\',
      \'translate\' => \'0\',
      \'type\' => \'campaign\',
      \'uid\' => \'1\',
      \'uuid\' => \'6070562f-384a-4818-8dfb-cc7e87c2c2a0\',
      \'vid\' => NULL,
      \'vuuid\' => \'95c0bc60-9d37-4286-830c-343d8904688a\',
    ),
  (object) array(
      \'body\' => array(
        \'und\' => array(
          array(
            \'value\' => "<p>I’m running to inject progressive thinking and patriotism to governance. I’m running to ensure the basic necessities needed to live a decent and productive life are available to my constituents. I’m running to empower my people.</p>\\r\\n",
            \'summary\' => \'\',
            \'format\' => \'filtered_html\',
            \'safe_value\' => "<p>I’m running to inject progressive thinking and patriotism to governance. I’m running to ensure the basic necessities needed to live a decent and productive life are available to my constituents. I’m running to empower my people.</p>\\n",
            \'safe_summary\' => \'\',
          ),
        ),
      ),
      \'changed\' => NULL,
      \'cid\' => \'0\',
      \'comment\' => \'2\',
      \'comment_count\' => \'0\',
      \'created\' => NULL,
      \'data\' => \'a:1:{s:7:"overlay";i:1;}\',
      \'field_account_name\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Terseer Ugbor\',
            \'format\' => NULL,
            \'safe_value\' => \'Terseer Ugbor\',
          ),
        ),
      ),
      \'field_account_number\' => array(
        \'und\' => array(
          array(
            \'value\' => \'0080713619\',
            \'format\' => NULL,
            \'safe_value\' => \'0080713619\',
          ),
        ),
      ),
      \'field_bank_name\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Diamond bank\',
            \'format\' => NULL,
            \'safe_value\' => \'Diamond bank\',
          ),
        ),
      ),
      \'field_date_of_birth\' => array(
        \'und\' => array(
          array(
            \'value\' => \'1980-05-20 00:00:00\',
            \'timezone\' => \'Africa/Lagos\',
            \'timezone_db\' => \'Africa/Lagos\',
            \'date_type\' => \'datetime\',
          ),
        ),
      ),
      \'field_education\' => array(
        \'und\' => array(
          array(
            \'value\' => \'7\',
            \'revision_id\' => \'7\',
          ),
          array(
            \'value\' => \'8\',
            \'revision_id\' => \'8\',
          ),
          array(
            \'value\' => \'9\',
            \'revision_id\' => \'9\',
          ),
        ),
      ),
      \'field_email\' => array(
        \'und\' => array(
          array(
            \'email\' => \'terseerugbor@gmail.com\',
          ),
        ),
      ),
      \'field_facebook_page\' => array(
        \'und\' => array(
          array(
            \'value\' => \'facebook.com/terseer.ugbor\',
            \'format\' => NULL,
            \'safe_value\' => \'facebook.com/terseer.ugbor\',
          ),
        ),
      ),
      \'field_first_name\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Terseer\',
            \'format\' => NULL,
            \'safe_value\' => \'Terseer\',
          ),
        ),
      ),
      \'field_instagram_handle\' => array(),
      \'field_last_name\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Ugboor\',
            \'format\' => NULL,
            \'safe_value\' => \'Ugboor\',
          ),
        ),
      ),
      \'field_linkedin_page\' => array(),
      \'field_manifesto\' => array(),
      \'field_middle_name\' => array(),
      \'field_personal_title\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Mr\',
          ),
        ),
      ),
      \'field_phone\' => array(
        \'und\' => array(
          array(
            \'value\' => \'08033165162\',
            \'format\' => NULL,
            \'safe_value\' => \'08033165162\',
          ),
        ),
      ),
      \'field_political_party\' => array(
        \'und\' => array(
          array(
            \'tid\' => \'2886\',
          ),
        ),
      ),
      \'field_position_running_for\' => array(
        \'und\' => array(
          array(
            \'tid\' => \'1837\',
          ),
        ),
      ),
      \'field_profile_image\' => array(
        \'und\' => array(
          array(
            \'fid\' => \'86\',
            \'uid\' => \'1\',
            \'filename\' => \'ugbor.jpg\',
            \'uri\' => \'public://ugbor.jpg\',
            \'filemime\' => \'image/jpeg\',
            \'filesize\' => \'86043\',
            \'status\' => \'1\',
            \'timestamp\' => \'1529934938\',
            \'type\' => \'image\',
            \'uuid\' => \'b7a67aff-6f39-489d-845c-17edbf09869c\',
            \'field_file_image_alt_text\' => array(),
            \'field_file_image_title_text\' => array(),
            \'rdf_mapping\' => array(),
            \'metadata\' => array(
              \'height\' => 624,
              \'width\' => 446,
            ),
            \'height\' => \'624\',
            \'width\' => \'446\',
            \'alt\' => \'\',
            \'title\' => \'\',
          ),
        ),
      ),
      \'field_resume_cv\' => array(),
      \'field_twitter_handle\' => array(),
      \'field_website\' => array(),
      \'files\' => array(),
      \'language\' => \'und\',
      \'last_comment_name\' => NULL,
      \'last_comment_timestamp\' => NULL,
      \'last_comment_uid\' => \'1\',
      \'log\' => \'\',
      \'menu\' => NULL,
      \'name\' => \'campaign\',
      \'nid\' => NULL,
      \'node_export_drupal_version\' => \'7\',
      \'path\' => NULL,
      \'picture\' => \'0\',
      \'promote\' => \'0\',
      \'rdf_mapping\' => array(
        \'rdftype\' => array(
          \'sioc:Item\',
          \'foaf:Document\',
        ),
        \'title\' => array(
          \'predicates\' => array(
            \'dc:title\',
          ),
        ),
        \'created\' => array(
          \'predicates\' => array(
            \'dc:date\',
            \'dc:created\',
          ),
          \'datatype\' => \'xsd:dateTime\',
          \'callback\' => \'date_iso8601\',
        ),
        \'changed\' => array(
          \'predicates\' => array(
            \'dc:modified\',
          ),
          \'datatype\' => \'xsd:dateTime\',
          \'callback\' => \'date_iso8601\',
        ),
        \'body\' => array(
          \'predicates\' => array(
            \'content:encoded\',
          ),
        ),
        \'uid\' => array(
          \'predicates\' => array(
            \'sioc:has_creator\',
          ),
          \'type\' => \'rel\',
        ),
        \'name\' => array(
          \'predicates\' => array(
            \'foaf:name\',
          ),
        ),
        \'comment_count\' => array(
          \'predicates\' => array(
            \'sioc:num_replies\',
          ),
          \'datatype\' => \'xsd:integer\',
        ),
        \'last_activity\' => array(
          \'predicates\' => array(
            \'sioc:last_activity_date\',
          ),
          \'datatype\' => \'xsd:dateTime\',
          \'callback\' => \'date_iso8601\',
        ),
      ),
      \'revision_timestamp\' => NULL,
      \'revision_uid\' => \'1\',
      \'status\' => \'0\',
      \'sticky\' => \'0\',
      \'title\' => \'Mr Terseer Ugboor for Kwande East, Benue, House of Assembly\',
      \'tnid\' => \'0\',
      \'translate\' => \'0\',
      \'type\' => \'campaign\',
      \'uid\' => \'1\',
      \'uuid\' => \'61e66f59-6048-408e-af13-36f6d972be38\',
      \'vid\' => NULL,
      \'vuuid\' => \'d5c7a2b5-1634-4351-8b0e-933566ee9585\',
    ),
  (object) array(
      \'body\' => array(
        \'und\' => array(
          array(
            \'value\' => "<p><strong>I am running for the position in order to introduce&nbsp; some sets of legislations that would address the challenges faced by my constituents in the area of agriculture which is a major preoccupation in the area. Some of these challenges includes; lack of storage facilities for farm produce, unsafe water transportation, annual flooding of the area which destroys farmlands, harvest and properties, and creating access to cheap finance for agriculture, including addressing the inadequate health care facilities in the area</strong></p>\\r\\n",
            \'summary\' => \'\',
            \'format\' => \'filtered_html\',
            \'safe_value\' => "<p><strong>I am running for the position in order to introduce  some sets of legislations that would address the challenges faced by my constituents in the area of agriculture which is a major preoccupation in the area. Some of these challenges includes; lack of storage facilities for farm produce, unsafe water transportation, annual flooding of the area which destroys farmlands, harvest and properties, and creating access to cheap finance for agriculture, including addressing the inadequate health care facilities in the area</strong></p>\\n",
            \'safe_summary\' => \'\',
          ),
        ),
      ),
      \'changed\' => NULL,
      \'cid\' => \'0\',
      \'comment\' => \'2\',
      \'comment_count\' => \'0\',
      \'created\' => NULL,
      \'data\' => \'a:1:{s:7:"overlay";i:1;}\',
      \'field_account_name\' => array(
        \'und\' => array(
          array(
            \'value\' => \'NNAMDI EMMANUEL ANEKWE-CHIVE\',
            \'format\' => NULL,
            \'safe_value\' => \'NNAMDI EMMANUEL ANEKWE-CHIVE\',
          ),
        ),
      ),
      \'field_account_number\' => array(
        \'und\' => array(
          array(
            \'value\' => \'0032575290\',
            \'format\' => NULL,
            \'safe_value\' => \'0032575290\',
          ),
        ),
      ),
      \'field_bank_name\' => array(
        \'und\' => array(
          array(
            \'value\' => \'STERLING BANK\',
            \'format\' => NULL,
            \'safe_value\' => \'STERLING BANK\',
          ),
        ),
      ),
      \'field_date_of_birth\' => array(
        \'und\' => array(
          array(
            \'value\' => \'1981-06-19 00:00:00\',
            \'timezone\' => \'Africa/Lagos\',
            \'timezone_db\' => \'Africa/Lagos\',
            \'date_type\' => \'datetime\',
          ),
        ),
      ),
      \'field_education\' => array(
        \'und\' => array(
          array(
            \'value\' => \'17\',
            \'revision_id\' => \'17\',
          ),
          array(
            \'value\' => \'18\',
            \'revision_id\' => \'18\',
          ),
          array(
            \'value\' => \'19\',
            \'revision_id\' => \'19\',
          ),
        ),
      ),
      \'field_email\' => array(
        \'und\' => array(
          array(
            \'email\' => \'nuelnnamdi@yahoo.com\',
          ),
        ),
      ),
      \'field_facebook_page\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Nnamdi Anekwe-Chive\',
            \'format\' => NULL,
            \'safe_value\' => \'Nnamdi Anekwe-Chive\',
          ),
        ),
      ),
      \'field_first_name\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Nnamdi\',
            \'format\' => NULL,
            \'safe_value\' => \'Nnamdi\',
          ),
        ),
      ),
      \'field_instagram_handle\' => array(
        \'und\' => array(
          array(
            \'value\' => \'@anekwechive\',
            \'format\' => NULL,
            \'safe_value\' => \'@anekwechive\',
          ),
        ),
      ),
      \'field_last_name\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Anekwe-Chive\',
            \'format\' => NULL,
            \'safe_value\' => \'Anekwe-Chive\',
          ),
        ),
      ),
      \'field_linkedin_page\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Nnamdi Anekwe-Chive\',
            \'format\' => NULL,
            \'safe_value\' => \'Nnamdi Anekwe-Chive\',
          ),
        ),
      ),
      \'field_manifesto\' => array(),
      \'field_middle_name\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Emmanuel\',
            \'format\' => NULL,
            \'safe_value\' => \'Emmanuel\',
          ),
        ),
      ),
      \'field_personal_title\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Mr\',
          ),
        ),
      ),
      \'field_phone\' => array(
        \'und\' => array(
          array(
            \'value\' => \'08033158004\',
            \'format\' => NULL,
            \'safe_value\' => \'08033158004\',
          ),
        ),
      ),
      \'field_political_party\' => array(
        \'und\' => array(
          array(
            \'tid\' => \'2924\',
          ),
        ),
      ),
      \'field_position_running_for\' => array(
        \'und\' => array(
          array(
            \'tid\' => \'1713\',
          ),
        ),
      ),
      \'field_profile_image\' => array(
        \'und\' => array(
          array(
            \'fid\' => \'91\',
            \'uid\' => \'1\',
            \'filename\' => \'20180604_002225.jpg\',
            \'uri\' => \'public://20180604_002225.jpg\',
            \'filemime\' => \'image/jpeg\',
            \'filesize\' => \'250773\',
            \'status\' => \'1\',
            \'timestamp\' => \'1529938727\',
            \'type\' => \'image\',
            \'uuid\' => \'656d4367-6e29-4e28-8ee5-ded3b2bdaeb1\',
            \'field_file_image_alt_text\' => array(),
            \'field_file_image_title_text\' => array(),
            \'rdf_mapping\' => array(),
            \'metadata\' => array(
              \'height\' => 1014,
              \'width\' => 1080,
            ),
            \'height\' => \'1014\',
            \'width\' => \'1080\',
            \'alt\' => \'\',
            \'title\' => \'\',
          ),
        ),
      ),
      \'field_resume_cv\' => array(),
      \'field_twitter_handle\' => array(
        \'und\' => array(
          array(
            \'value\' => \'@nnamdianekwe\',
            \'format\' => NULL,
            \'safe_value\' => \'@nnamdianekwe\',
          ),
        ),
      ),
      \'field_website\' => array(),
      \'files\' => array(),
      \'language\' => \'und\',
      \'last_comment_name\' => NULL,
      \'last_comment_timestamp\' => NULL,
      \'last_comment_uid\' => \'1\',
      \'log\' => \'\',
      \'menu\' => NULL,
      \'name\' => \'campaign\',
      \'nid\' => NULL,
      \'node_export_drupal_version\' => \'7\',
      \'path\' => NULL,
      \'picture\' => \'0\',
      \'promote\' => \'0\',
      \'rdf_mapping\' => array(
        \'rdftype\' => array(
          \'sioc:Item\',
          \'foaf:Document\',
        ),
        \'title\' => array(
          \'predicates\' => array(
            \'dc:title\',
          ),
        ),
        \'created\' => array(
          \'predicates\' => array(
            \'dc:date\',
            \'dc:created\',
          ),
          \'datatype\' => \'xsd:dateTime\',
          \'callback\' => \'date_iso8601\',
        ),
        \'changed\' => array(
          \'predicates\' => array(
            \'dc:modified\',
          ),
          \'datatype\' => \'xsd:dateTime\',
          \'callback\' => \'date_iso8601\',
        ),
        \'body\' => array(
          \'predicates\' => array(
            \'content:encoded\',
          ),
        ),
        \'uid\' => array(
          \'predicates\' => array(
            \'sioc:has_creator\',
          ),
          \'type\' => \'rel\',
        ),
        \'name\' => array(
          \'predicates\' => array(
            \'foaf:name\',
          ),
        ),
        \'comment_count\' => array(
          \'predicates\' => array(
            \'sioc:num_replies\',
          ),
          \'datatype\' => \'xsd:integer\',
        ),
        \'last_activity\' => array(
          \'predicates\' => array(
            \'sioc:last_activity_date\',
          ),
          \'datatype\' => \'xsd:dateTime\',
          \'callback\' => \'date_iso8601\',
        ),
      ),
      \'revision_timestamp\' => NULL,
      \'revision_uid\' => \'1\',
      \'status\' => \'0\',
      \'sticky\' => \'0\',
      \'title\' => \'Mr Nnamdi Anekwe-Chive for Anambra West, Anambra, House of Assembly\',
      \'tnid\' => \'0\',
      \'translate\' => \'0\',
      \'type\' => \'campaign\',
      \'uid\' => \'1\',
      \'uuid\' => \'896a909c-2db9-4875-b44a-f458c335e257\',
      \'vid\' => NULL,
      \'vuuid\' => \'cd89577f-7822-4b1c-a5da-d93699efd7ee\',
    ),
  (object) array(
      \'body\' => array(
        \'und\' => array(
          array(
            \'value\' => "<p>I have always been very concerned about our constituency’s backwardness in terms of economy, socio-cultural, Agriculture and Security. I believe there are workable solutions available that will enhance development of our young stars, equip our women with modern skills that will help them to be self-reliant, build a good security network that will secure our families. I would like to see a productive society with maximum security, better infrastructure that will enable our children have a taste of modern society, modern facilities that will enhance entrepreneurs development and above all a better representation that listen to the yarning and aspiration of our people while projecting their interest at the National Assembly for improve and better livelihood of our people in Akwanga, Nassarawa Eggon &amp; Wamba Federal Constituency.</p>\\r\\n",
            \'summary\' => \'\',
            \'format\' => \'filtered_html\',
            \'safe_value\' => "<p>I have always been very concerned about our constituency’s backwardness in terms of economy, socio-cultural, Agriculture and Security. I believe there are workable solutions available that will enhance development of our young stars, equip our women with modern skills that will help them to be self-reliant, build a good security network that will secure our families. I would like to see a productive society with maximum security, better infrastructure that will enable our children have a taste of modern society, modern facilities that will enhance entrepreneurs development and above all a better representation that listen to the yarning and aspiration of our people while projecting their interest at the National Assembly for improve and better livelihood of our people in Akwanga, Nassarawa Eggon &amp; Wamba Federal Constituency.</p>\\n",
            \'safe_summary\' => \'\',
          ),
        ),
      ),
      \'changed\' => NULL,
      \'cid\' => \'0\',
      \'comment\' => \'2\',
      \'comment_count\' => \'0\',
      \'created\' => NULL,
      \'data\' => \'a:1:{s:7:"overlay";i:1;}\',
      \'field_account_name\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Kefas Tigga\',
            \'format\' => NULL,
            \'safe_value\' => \'Kefas Tigga\',
          ),
        ),
      ),
      \'field_account_number\' => array(
        \'und\' => array(
          array(
            \'value\' => \'2083273623\',
            \'format\' => NULL,
            \'safe_value\' => \'2083273623\',
          ),
        ),
      ),
      \'field_bank_name\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Zenith Bank\',
            \'format\' => NULL,
            \'safe_value\' => \'Zenith Bank\',
          ),
        ),
      ),
      \'field_date_of_birth\' => array(
        \'und\' => array(
          array(
            \'value\' => \'1980-12-09 00:00:00\',
            \'timezone\' => \'Africa/Lagos\',
            \'timezone_db\' => \'Africa/Lagos\',
            \'date_type\' => \'datetime\',
          ),
        ),
      ),
      \'field_education\' => array(
        \'und\' => array(
          array(
            \'value\' => \'12\',
            \'revision_id\' => \'12\',
          ),
        ),
      ),
      \'field_email\' => array(
        \'und\' => array(
          array(
            \'email\' => \'keftigga@gmail.com\',
          ),
        ),
      ),
      \'field_facebook_page\' => array(
        \'und\' => array(
          array(
            \'value\' => \'kefas tigga for reps 2019\',
            \'format\' => NULL,
            \'safe_value\' => \'kefas tigga for reps 2019\',
          ),
        ),
      ),
      \'field_first_name\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Kefas\',
            \'format\' => NULL,
            \'safe_value\' => \'Kefas\',
          ),
        ),
      ),
      \'field_instagram_handle\' => array(
        \'und\' => array(
          array(
            \'value\' => \'keftigga\',
            \'format\' => NULL,
            \'safe_value\' => \'keftigga\',
          ),
        ),
      ),
      \'field_last_name\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Tigga\',
            \'format\' => NULL,
            \'safe_value\' => \'Tigga\',
          ),
        ),
      ),
      \'field_linkedin_page\' => array(),
      \'field_manifesto\' => array(),
      \'field_middle_name\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Elisha\',
            \'format\' => NULL,
            \'safe_value\' => \'Elisha\',
          ),
        ),
      ),
      \'field_personal_title\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Mr\',
          ),
        ),
      ),
      \'field_phone\' => array(
        \'und\' => array(
          array(
            \'value\' => \'08037406461\',
            \'format\' => NULL,
            \'safe_value\' => \'08037406461\',
          ),
        ),
      ),
      \'field_political_party\' => array(
        \'und\' => array(
          array(
            \'tid\' => \'2924\',
          ),
        ),
      ),
      \'field_position_running_for\' => array(
        \'und\' => array(
          array(
            \'tid\' => \'1536\',
          ),
        ),
      ),
      \'field_profile_image\' => array(
        \'und\' => array(
          array(
            \'fid\' => \'89\',
            \'uid\' => \'1\',
            \'filename\' => \'7W8B4890.JPG\',
            \'uri\' => \'public://7W8B4890.JPG\',
            \'filemime\' => \'image/jpeg\',
            \'filesize\' => \'5575060\',
            \'status\' => \'1\',
            \'timestamp\' => \'1529936883\',
            \'type\' => \'image\',
            \'uuid\' => \'3e1aa1ff-7ebb-4375-886c-fb6eb7b6d2bc\',
            \'field_file_image_alt_text\' => array(),
            \'field_file_image_title_text\' => array(),
            \'rdf_mapping\' => array(),
            \'metadata\' => array(
              \'height\' => 5760,
              \'width\' => 3840,
            ),
            \'height\' => \'5760\',
            \'width\' => \'3840\',
            \'alt\' => \'\',
            \'title\' => \'\',
          ),
        ),
      ),
      \'field_resume_cv\' => array(),
      \'field_twitter_handle\' => array(
        \'und\' => array(
          array(
            \'value\' => \'@keftigga\',
            \'format\' => NULL,
            \'safe_value\' => \'@keftigga\',
          ),
        ),
      ),
      \'field_website\' => array(),
      \'files\' => array(),
      \'language\' => \'und\',
      \'last_comment_name\' => NULL,
      \'last_comment_timestamp\' => NULL,
      \'last_comment_uid\' => \'1\',
      \'log\' => \'\',
      \'menu\' => NULL,
      \'name\' => \'campaign\',
      \'nid\' => NULL,
      \'node_export_drupal_version\' => \'7\',
      \'path\' => NULL,
      \'picture\' => \'0\',
      \'promote\' => \'0\',
      \'rdf_mapping\' => array(
        \'rdftype\' => array(
          \'sioc:Item\',
          \'foaf:Document\',
        ),
        \'title\' => array(
          \'predicates\' => array(
            \'dc:title\',
          ),
        ),
        \'created\' => array(
          \'predicates\' => array(
            \'dc:date\',
            \'dc:created\',
          ),
          \'datatype\' => \'xsd:dateTime\',
          \'callback\' => \'date_iso8601\',
        ),
        \'changed\' => array(
          \'predicates\' => array(
            \'dc:modified\',
          ),
          \'datatype\' => \'xsd:dateTime\',
          \'callback\' => \'date_iso8601\',
        ),
        \'body\' => array(
          \'predicates\' => array(
            \'content:encoded\',
          ),
        ),
        \'uid\' => array(
          \'predicates\' => array(
            \'sioc:has_creator\',
          ),
          \'type\' => \'rel\',
        ),
        \'name\' => array(
          \'predicates\' => array(
            \'foaf:name\',
          ),
        ),
        \'comment_count\' => array(
          \'predicates\' => array(
            \'sioc:num_replies\',
          ),
          \'datatype\' => \'xsd:integer\',
        ),
        \'last_activity\' => array(
          \'predicates\' => array(
            \'sioc:last_activity_date\',
          ),
          \'datatype\' => \'xsd:dateTime\',
          \'callback\' => \'date_iso8601\',
        ),
      ),
      \'revision_timestamp\' => NULL,
      \'revision_uid\' => \'1\',
      \'status\' => \'0\',
      \'sticky\' => \'0\',
      \'title\' => \'Mr Kefas Tigga for Akwanga/Nassarawa Eggon/ Wamba, Nasarawa, House of Representatives\',
      \'tnid\' => \'0\',
      \'translate\' => \'0\',
      \'type\' => \'campaign\',
      \'uid\' => \'1\',
      \'uuid\' => \'8c3d8380-4e6c-4fa3-be4a-14a3bcadb982\',
      \'vid\' => NULL,
      \'vuuid\' => \'fdd8a120-8aae-4302-b53f-9a4e4ced0715\',
    ),
  (object) array(
      \'body\' => array(
        \'und\' => array(
          array(
            \'value\' => "<p>To help my constituency. Ukwa needs accountable leadership, provision of oportunities and services. My skills, experience&nbsp;and exposure will fill this needs.</p>\\r\\n",
            \'summary\' => \'\',
            \'format\' => \'filtered_html\',
            \'safe_value\' => "<p>To help my constituency. Ukwa needs accountable leadership, provision of oportunities and services. My skills, experience and exposure will fill this needs.</p>\\n",
            \'safe_summary\' => \'\',
          ),
        ),
      ),
      \'changed\' => NULL,
      \'cid\' => \'0\',
      \'comment\' => \'2\',
      \'comment_count\' => \'0\',
      \'created\' => NULL,
      \'data\' => \'a:1:{s:7:"overlay";i:1;}\',
      \'field_account_name\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Ejikeme Alozie-Nwagboso\',
            \'format\' => NULL,
            \'safe_value\' => \'Ejikeme Alozie-Nwagboso\',
          ),
        ),
      ),
      \'field_account_number\' => array(
        \'und\' => array(
          array(
            \'value\' => \'0002597836\',
            \'format\' => NULL,
            \'safe_value\' => \'0002597836\',
          ),
        ),
      ),
      \'field_bank_name\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Access Bank\',
            \'format\' => NULL,
            \'safe_value\' => \'Access Bank\',
          ),
        ),
      ),
      \'field_date_of_birth\' => array(
        \'und\' => array(
          array(
            \'value\' => \'1982-05-09 00:00:00\',
            \'timezone\' => \'Africa/Lagos\',
            \'timezone_db\' => \'Africa/Lagos\',
            \'date_type\' => \'datetime\',
          ),
        ),
      ),
      \'field_education\' => array(
        \'und\' => array(
          array(
            \'value\' => \'10\',
            \'revision_id\' => \'10\',
          ),
          array(
            \'value\' => \'11\',
            \'revision_id\' => \'11\',
          ),
        ),
      ),
      \'field_email\' => array(
        \'und\' => array(
          array(
            \'email\' => \'e.alozienwagboso@gmail.com\',
          ),
        ),
      ),
      \'field_facebook_page\' => array(),
      \'field_first_name\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Ejikeme\',
            \'format\' => NULL,
            \'safe_value\' => \'Ejikeme\',
          ),
        ),
      ),
      \'field_instagram_handle\' => array(
        \'und\' => array(
          array(
            \'value\' => \'enwagboso\',
            \'format\' => NULL,
            \'safe_value\' => \'enwagboso\',
          ),
        ),
      ),
      \'field_last_name\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Alozie-Nwagboso\',
            \'format\' => NULL,
            \'safe_value\' => \'Alozie-Nwagboso\',
          ),
        ),
      ),
      \'field_linkedin_page\' => array(),
      \'field_manifesto\' => array(),
      \'field_middle_name\' => array(),
      \'field_personal_title\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Mr\',
          ),
        ),
      ),
      \'field_phone\' => array(),
      \'field_political_party\' => array(
        \'und\' => array(
          array(
            \'tid\' => \'2888\',
          ),
        ),
      ),
      \'field_position_running_for\' => array(
        \'und\' => array(
          array(
            \'tid\' => \'1266\',
          ),
        ),
      ),
      \'field_profile_image\' => array(
        \'und\' => array(
          array(
            \'fid\' => \'87\',
            \'uid\' => \'1\',
            \'filename\' => \'image1.jpeg\',
            \'uri\' => \'public://image1.jpeg\',
            \'filemime\' => \'image/jpeg\',
            \'filesize\' => \'23391\',
            \'status\' => \'1\',
            \'timestamp\' => \'1529936182\',
            \'type\' => \'image\',
            \'uuid\' => \'5712e383-bdcf-4d3c-88da-9a76bcb19cb8\',
            \'field_file_image_alt_text\' => array(),
            \'field_file_image_title_text\' => array(),
            \'rdf_mapping\' => array(),
            \'metadata\' => array(
              \'height\' => 640,
              \'width\' => 640,
            ),
            \'height\' => \'640\',
            \'width\' => \'640\',
            \'alt\' => \'\',
            \'title\' => \'\',
          ),
        ),
      ),
      \'field_resume_cv\' => array(
        \'und\' => array(
          array(
            \'fid\' => \'88\',
            \'uid\' => \'1\',
            \'filename\' => \'Copy of E.J_Alozie-Nwagboso Resume NG.docx\',
            \'uri\' => \'public://Copy of E.J_Alozie-Nwagboso Resume NG.docx\',
            \'filemime\' => \'application/vnd.openxmlformats-officedocument.wordprocessingml.document\',
            \'filesize\' => \'488665\',
            \'status\' => \'1\',
            \'timestamp\' => \'1529936182\',
            \'type\' => \'document\',
            \'uuid\' => \'85d9ba76-0928-419a-a0d8-f9bd268887ca\',
            \'rdf_mapping\' => array(),
            \'metadata\' => array(),
            \'display\' => \'1\',
            \'description\' => \'\',
          ),
        ),
      ),
      \'field_twitter_handle\' => array(
        \'und\' => array(
          array(
            \'value\' => \'@enwagboso\',
            \'format\' => NULL,
            \'safe_value\' => \'@enwagboso\',
          ),
        ),
      ),
      \'field_website\' => array(),
      \'files\' => array(),
      \'language\' => \'und\',
      \'last_comment_name\' => NULL,
      \'last_comment_timestamp\' => NULL,
      \'last_comment_uid\' => \'1\',
      \'log\' => \'\',
      \'menu\' => NULL,
      \'name\' => \'campaign\',
      \'nid\' => NULL,
      \'node_export_drupal_version\' => \'7\',
      \'path\' => NULL,
      \'picture\' => \'0\',
      \'promote\' => \'0\',
      \'rdf_mapping\' => array(
        \'rdftype\' => array(
          \'sioc:Item\',
          \'foaf:Document\',
        ),
        \'title\' => array(
          \'predicates\' => array(
            \'dc:title\',
          ),
        ),
        \'created\' => array(
          \'predicates\' => array(
            \'dc:date\',
            \'dc:created\',
          ),
          \'datatype\' => \'xsd:dateTime\',
          \'callback\' => \'date_iso8601\',
        ),
        \'changed\' => array(
          \'predicates\' => array(
            \'dc:modified\',
          ),
          \'datatype\' => \'xsd:dateTime\',
          \'callback\' => \'date_iso8601\',
        ),
        \'body\' => array(
          \'predicates\' => array(
            \'content:encoded\',
          ),
        ),
        \'uid\' => array(
          \'predicates\' => array(
            \'sioc:has_creator\',
          ),
          \'type\' => \'rel\',
        ),
        \'name\' => array(
          \'predicates\' => array(
            \'foaf:name\',
          ),
        ),
        \'comment_count\' => array(
          \'predicates\' => array(
            \'sioc:num_replies\',
          ),
          \'datatype\' => \'xsd:integer\',
        ),
        \'last_activity\' => array(
          \'predicates\' => array(
            \'sioc:last_activity_date\',
          ),
          \'datatype\' => \'xsd:dateTime\',
          \'callback\' => \'date_iso8601\',
        ),
      ),
      \'revision_timestamp\' => NULL,
      \'revision_uid\' => \'1\',
      \'status\' => \'0\',
      \'sticky\' => \'0\',
      \'title\' => \'Mr Ejikeme Alozie-Nwagboso for Ukwa East/Ukwa West, Abia, House of Representatives\',
      \'tnid\' => \'0\',
      \'translate\' => \'0\',
      \'type\' => \'campaign\',
      \'uid\' => \'1\',
      \'uuid\' => \'9581fb72-f7cb-4eb1-9e6e-dee26b184690\',
      \'vid\' => NULL,
      \'vuuid\' => \'e9be1ac6-5e21-484d-94a8-7ec1a5a7ee03\',
    ),
  (object) array(
      \'body\' => array(
        \'und\' => array(
          array(
            \'value\' => "<p><strong>To lead a united, informed and prosperous constituency, to peacefully and democratically cultivate the spirit of self reliance among my people, by advocating against factors that bring underdevelopment </strong></p>\\r\\n",
            \'summary\' => \'\',
            \'format\' => \'filtered_html\',
            \'safe_value\' => "<p><strong>To lead a united, informed and prosperous constituency, to peacefully and democratically cultivate the spirit of self reliance among my people, by advocating against factors that bring underdevelopment </strong></p>\\n",
            \'safe_summary\' => \'\',
          ),
        ),
      ),
      \'changed\' => NULL,
      \'cid\' => \'0\',
      \'comment\' => \'2\',
      \'comment_count\' => \'0\',
      \'created\' => NULL,
      \'data\' => \'a:1:{s:7:"overlay";i:1;}\',
      \'field_account_name\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Adakole Oko Daniel\',
            \'format\' => NULL,
            \'safe_value\' => \'Adakole Oko Daniel\',
          ),
        ),
      ),
      \'field_account_number\' => array(
        \'und\' => array(
          array(
            \'value\' => \'0002152518\',
            \'format\' => NULL,
            \'safe_value\' => \'0002152518\',
          ),
        ),
      ),
      \'field_bank_name\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Access Bank\',
            \'format\' => NULL,
            \'safe_value\' => \'Access Bank\',
          ),
        ),
      ),
      \'field_date_of_birth\' => array(
        \'und\' => array(
          array(
            \'value\' => \'1981-09-03 00:00:00\',
            \'timezone\' => \'Africa/Lagos\',
            \'timezone_db\' => \'Africa/Lagos\',
            \'date_type\' => \'datetime\',
          ),
        ),
      ),
      \'field_education\' => array(
        \'und\' => array(
          array(
            \'value\' => \'15\',
            \'revision_id\' => \'15\',
          ),
          array(
            \'value\' => \'16\',
            \'revision_id\' => \'16\',
          ),
        ),
      ),
      \'field_email\' => array(
        \'und\' => array(
          array(
            \'email\' => \'danyadakole@gmail.com\',
          ),
        ),
      ),
      \'field_facebook_page\' => array(),
      \'field_first_name\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Daniel\',
            \'format\' => NULL,
            \'safe_value\' => \'Daniel\',
          ),
        ),
      ),
      \'field_instagram_handle\' => array(),
      \'field_last_name\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Adakole\',
            \'format\' => NULL,
            \'safe_value\' => \'Adakole\',
          ),
        ),
      ),
      \'field_linkedin_page\' => array(),
      \'field_manifesto\' => array(),
      \'field_middle_name\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Oko\',
            \'format\' => NULL,
            \'safe_value\' => \'Oko\',
          ),
        ),
      ),
      \'field_personal_title\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Mr\',
          ),
        ),
      ),
      \'field_phone\' => array(
        \'und\' => array(
          array(
            \'value\' => \'08130623056\',
            \'format\' => NULL,
            \'safe_value\' => \'08130623056\',
          ),
        ),
      ),
      \'field_political_party\' => array(
        \'und\' => array(
          array(
            \'tid\' => \'2924\',
          ),
        ),
      ),
      \'field_position_running_for\' => array(
        \'und\' => array(
          array(
            \'tid\' => \'1847\',
          ),
        ),
      ),
      \'field_profile_image\' => array(
        \'und\' => array(
          array(
            \'fid\' => \'90\',
            \'uid\' => \'1\',
            \'filename\' => \'campaign pix s.jpg\',
            \'uri\' => \'public://campaign pix s.jpg\',
            \'filemime\' => \'image/jpeg\',
            \'filesize\' => \'52131\',
            \'status\' => \'1\',
            \'timestamp\' => \'1529937734\',
            \'type\' => \'image\',
            \'uuid\' => \'34ea6e27-51e1-4669-84a2-d27f0fdd8558\',
            \'field_file_image_alt_text\' => array(),
            \'field_file_image_title_text\' => array(),
            \'rdf_mapping\' => array(),
            \'metadata\' => array(
              \'height\' => 1050,
              \'width\' => 750,
            ),
            \'height\' => \'1050\',
            \'width\' => \'750\',
            \'alt\' => \'\',
            \'title\' => \'\',
          ),
        ),
      ),
      \'field_resume_cv\' => array(),
      \'field_twitter_handle\' => array(),
      \'field_website\' => array(),
      \'files\' => array(),
      \'language\' => \'und\',
      \'last_comment_name\' => NULL,
      \'last_comment_timestamp\' => NULL,
      \'last_comment_uid\' => \'1\',
      \'log\' => \'\',
      \'menu\' => NULL,
      \'name\' => \'campaign\',
      \'nid\' => NULL,
      \'node_export_drupal_version\' => \'7\',
      \'path\' => NULL,
      \'picture\' => \'0\',
      \'promote\' => \'0\',
      \'rdf_mapping\' => array(
        \'rdftype\' => array(
          \'sioc:Item\',
          \'foaf:Document\',
        ),
        \'title\' => array(
          \'predicates\' => array(
            \'dc:title\',
          ),
        ),
        \'created\' => array(
          \'predicates\' => array(
            \'dc:date\',
            \'dc:created\',
          ),
          \'datatype\' => \'xsd:dateTime\',
          \'callback\' => \'date_iso8601\',
        ),
        \'changed\' => array(
          \'predicates\' => array(
            \'dc:modified\',
          ),
          \'datatype\' => \'xsd:dateTime\',
          \'callback\' => \'date_iso8601\',
        ),
        \'body\' => array(
          \'predicates\' => array(
            \'content:encoded\',
          ),
        ),
        \'uid\' => array(
          \'predicates\' => array(
            \'sioc:has_creator\',
          ),
          \'type\' => \'rel\',
        ),
        \'name\' => array(
          \'predicates\' => array(
            \'foaf:name\',
          ),
        ),
        \'comment_count\' => array(
          \'predicates\' => array(
            \'sioc:num_replies\',
          ),
          \'datatype\' => \'xsd:integer\',
        ),
        \'last_activity\' => array(
          \'predicates\' => array(
            \'sioc:last_activity_date\',
          ),
          \'datatype\' => \'xsd:dateTime\',
          \'callback\' => \'date_iso8601\',
        ),
      ),
      \'revision_timestamp\' => NULL,
      \'revision_uid\' => \'1\',
      \'status\' => \'0\',
      \'sticky\' => \'0\',
      \'title\' => \'Mr Daniel Adakole for Otukpo, Benue, House of Assembly\',
      \'tnid\' => \'0\',
      \'translate\' => \'0\',
      \'type\' => \'campaign\',
      \'uid\' => \'1\',
      \'uuid\' => \'c11a85ff-2736-4262-b01e-8499f7e6d947\',
      \'vid\' => NULL,
      \'vuuid\' => \'81d3a5f5-d399-4fd0-86cf-4cc06428a46b\',
    ),
  (object) array(
      \'body\' => array(
        \'und\' => array(
          array(
            \'value\' => \'I will be running for the seat of Senate to offer my constituents qualitative representation and make good laws for the country. Besides this, I intend to use my network and experience gained in the private sector to attract socio economic development to the eight local governments that form my constituency. This will be achieved through sustainable partnerships with foreign companies and international NGOs.\',
            \'summary\' => \'\',
            \'format\' => \'html\',
            \'safe_value\' => \'I will be running for the seat of Senate to offer my constituents qualitative representation and make good laws for the country. Besides this, I intend to use my network and experience gained in the private sector to attract socio economic development to the eight local governments that form my constituency. This will be achieved through sustainable partnerships with foreign companies and international NGOs.\',
            \'safe_summary\' => \'\',
          ),
        ),
      ),
      \'changed\' => NULL,
      \'cid\' => \'0\',
      \'comment\' => \'2\',
      \'comment_count\' => \'0\',
      \'created\' => NULL,
      \'data\' => \'a:1:{s:7:"overlay";i:1;}\',
      \'field_account_name\' => array(
        \'und\' => array(
          array(
            \'value\' => \'RIJO SHEKARI\',
            \'format\' => NULL,
            \'safe_value\' => \'RIJO SHEKARI\',
          ),
        ),
      ),
      \'field_account_number\' => array(
        \'und\' => array(
          array(
            \'value\' => \'0114299609\',
            \'format\' => NULL,
            \'safe_value\' => \'0114299609\',
          ),
        ),
      ),
      \'field_bank_name\' => array(
        \'und\' => array(
          array(
            \'value\' => \'GTBANK\',
            \'format\' => NULL,
            \'safe_value\' => \'GTBANK\',
          ),
        ),
      ),
      \'field_date_of_birth\' => array(
        \'und\' => array(
          array(
            \'value\' => \'1979-11-22 00:00:00\',
            \'timezone\' => \'Africa/Lagos\',
            \'timezone_db\' => \'Africa/Lagos\',
            \'date_type\' => \'datetime\',
          ),
        ),
      ),
      \'field_education\' => array(
        \'und\' => array(
          array(
            \'value\' => \'22\',
            \'revision_id\' => \'22\',
          ),
          array(
            \'value\' => \'23\',
            \'revision_id\' => \'23\',
          ),
          array(
            \'value\' => \'24\',
            \'revision_id\' => \'24\',
          ),
        ),
      ),
      \'field_email\' => array(
        \'und\' => array(
          array(
            \'email\' => \'rijo_s@yahoo.com\',
          ),
        ),
      ),
      \'field_facebook_page\' => array(
        \'und\' => array(
          array(
            \'value\' => \'RIJO SHEKARI 2019 SUPPORT GROUP\',
            \'format\' => NULL,
            \'safe_value\' => \'RIJO SHEKARI 2019 SUPPORT GROUP\',
          ),
        ),
      ),
      \'field_first_name\' => array(
        \'und\' => array(
          array(
            \'value\' => \'SHEKARI\',
            \'format\' => NULL,
            \'safe_value\' => \'SHEKARI\',
          ),
        ),
      ),
      \'field_instagram_handle\' => array(),
      \'field_last_name\' => array(
        \'und\' => array(
          array(
            \'value\' => \'SHEKARI\',
            \'format\' => NULL,
            \'safe_value\' => \'SHEKARI\',
          ),
        ),
      ),
      \'field_linkedin_page\' => array(
        \'und\' => array(
          array(
            \'value\' => \'RIJO SHEKARI\',
            \'format\' => NULL,
            \'safe_value\' => \'RIJO SHEKARI\',
          ),
        ),
      ),
      \'field_manifesto\' => array(),
      \'field_middle_name\' => array(
        \'und\' => array(
          array(
            \'value\' => \'RIJO\',
            \'format\' => NULL,
            \'safe_value\' => \'RIJO\',
          ),
        ),
      ),
      \'field_personal_title\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Mr\',
          ),
        ),
      ),
      \'field_phone\' => array(
        \'und\' => array(
          array(
            \'value\' => \'08037016804\',
            \'format\' => NULL,
            \'safe_value\' => \'08037016804\',
          ),
        ),
      ),
      \'field_political_party\' => array(
        \'und\' => array(
          array(
            \'tid\' => \'2924\',
          ),
        ),
      ),
      \'field_position_running_for\' => array(
        \'und\' => array(
          array(
            \'tid\' => \'1182\',
          ),
        ),
      ),
      \'field_profile_image\' => array(
        \'und\' => array(
          array(
            \'fid\' => \'93\',
            \'uid\' => \'1\',
            \'filename\' => \'Potrait.jpeg\',
            \'uri\' => \'public://Potrait.jpeg\',
            \'filemime\' => \'image/jpeg\',
            \'filesize\' => \'38120\',
            \'status\' => \'1\',
            \'timestamp\' => \'1529939908\',
            \'type\' => \'image\',
            \'uuid\' => \'dfe7d833-fd41-4a28-b532-f4926f02c361\',
            \'field_file_image_alt_text\' => array(),
            \'field_file_image_title_text\' => array(),
            \'rdf_mapping\' => array(),
            \'metadata\' => array(
              \'height\' => 1080,
              \'width\' => 720,
            ),
            \'height\' => \'1080\',
            \'width\' => \'720\',
            \'alt\' => \'\',
            \'title\' => \'\',
          ),
        ),
      ),
      \'field_resume_cv\' => array(),
      \'field_twitter_handle\' => array(
        \'und\' => array(
          array(
            \'value\' => \'@lordRij\',
            \'format\' => NULL,
            \'safe_value\' => \'@lordRij\',
          ),
        ),
      ),
      \'field_website\' => array(),
      \'files\' => array(),
      \'language\' => \'und\',
      \'last_comment_name\' => NULL,
      \'last_comment_timestamp\' => NULL,
      \'last_comment_uid\' => \'1\',
      \'log\' => \'\',
      \'menu\' => NULL,
      \'name\' => \'campaign\',
      \'nid\' => NULL,
      \'node_export_drupal_version\' => \'7\',
      \'path\' => NULL,
      \'picture\' => \'0\',
      \'promote\' => \'0\',
      \'rdf_mapping\' => array(
        \'rdftype\' => array(
          \'sioc:Item\',
          \'foaf:Document\',
        ),
        \'title\' => array(
          \'predicates\' => array(
            \'dc:title\',
          ),
        ),
        \'created\' => array(
          \'predicates\' => array(
            \'dc:date\',
            \'dc:created\',
          ),
          \'datatype\' => \'xsd:dateTime\',
          \'callback\' => \'date_iso8601\',
        ),
        \'changed\' => array(
          \'predicates\' => array(
            \'dc:modified\',
          ),
          \'datatype\' => \'xsd:dateTime\',
          \'callback\' => \'date_iso8601\',
        ),
        \'body\' => array(
          \'predicates\' => array(
            \'content:encoded\',
          ),
        ),
        \'uid\' => array(
          \'predicates\' => array(
            \'sioc:has_creator\',
          ),
          \'type\' => \'rel\',
        ),
        \'name\' => array(
          \'predicates\' => array(
            \'foaf:name\',
          ),
        ),
        \'comment_count\' => array(
          \'predicates\' => array(
            \'sioc:num_replies\',
          ),
          \'datatype\' => \'xsd:integer\',
        ),
        \'last_activity\' => array(
          \'predicates\' => array(
            \'sioc:last_activity_date\',
          ),
          \'datatype\' => \'xsd:dateTime\',
          \'callback\' => \'date_iso8601\',
        ),
      ),
      \'revision_timestamp\' => NULL,
      \'revision_uid\' => \'1\',
      \'status\' => \'0\',
      \'sticky\' => \'0\',
      \'title\' => \'Mr SHEKARI SHEKARI for Kaduna South, Kaduna, Senator\',
      \'tnid\' => \'0\',
      \'translate\' => \'0\',
      \'type\' => \'campaign\',
      \'uid\' => \'1\',
      \'uuid\' => \'c9f756ae-55cf-4774-9b46-9c9738bf2a1b\',
      \'vid\' => NULL,
      \'vuuid\' => \'b5b437ed-4887-4d31-b157-daad43af16d1\',
    ),
  (object) array(
      \'body\' => array(
        \'und\' => array(
          array(
            \'value\' => "<p><strong>1.To provide effective representation to my constituency by actively engaging them in legislative processes. </strong></p>\\r\\n\\r\\n<p><strong>2. To mobilize like-minds in the NASS to provide the necessary legislative framework for restructuring of Nigeria.</strong></p>\\r\\n\\r\\n<p><strong>3. To sponsor bills that will contribute to the development of the country such as equal right to quality health care bill, public officer responsibilities bill etc.</strong></p>\\r\\n\\r\\n<p><strong>4. To provide effective oversight on the use of donor funds including loans from multilateral and bilateral institutions through the House committee on Loans, Aids and Debts.</strong></p>\\r\\n\\r\\n<p><strong>5. To support developmental efforts of my State government by actively lobbying for federal interventions and appointments for my constituency and State.</strong></p>\\r\\n",
            \'summary\' => \'\',
            \'format\' => \'filtered_html\',
            \'safe_value\' => "<p><strong>1.To provide effective representation to my constituency by actively engaging them in legislative processes. </strong></p>\\n<p><strong>2. To mobilize like-minds in the NASS to provide the necessary legislative framework for restructuring of Nigeria.</strong></p>\\n<p><strong>3. To sponsor bills that will contribute to the development of the country such as equal right to quality health care bill, public officer responsibilities bill etc.</strong></p>\\n<p><strong>4. To provide effective oversight on the use of donor funds including loans from multilateral and bilateral institutions through the House committee on Loans, Aids and Debts.</strong></p>\\n<p><strong>5. To support developmental efforts of my State government by actively lobbying for federal interventions and appointments for my constituency and State.</strong></p>\\n",
            \'safe_summary\' => \'\',
          ),
        ),
      ),
      \'changed\' => NULL,
      \'cid\' => \'0\',
      \'comment\' => \'2\',
      \'comment_count\' => \'0\',
      \'created\' => NULL,
      \'data\' => \'a:1:{s:7:"overlay";i:1;}\',
      \'field_account_name\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Michael Olugbile\',
            \'format\' => NULL,
            \'safe_value\' => \'Michael Olugbile\',
          ),
        ),
      ),
      \'field_account_number\' => array(
        \'und\' => array(
          array(
            \'value\' => \'0019484474\',
            \'format\' => NULL,
            \'safe_value\' => \'0019484474\',
          ),
        ),
      ),
      \'field_bank_name\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Stanbic IBTC\',
            \'format\' => NULL,
            \'safe_value\' => \'Stanbic IBTC\',
          ),
        ),
      ),
      \'field_date_of_birth\' => array(
        \'und\' => array(
          array(
            \'value\' => \'1982-07-27 00:00:00\',
            \'timezone\' => \'Africa/Lagos\',
            \'timezone_db\' => \'Africa/Lagos\',
            \'date_type\' => \'datetime\',
          ),
        ),
      ),
      \'field_education\' => array(
        \'und\' => array(
          array(
            \'value\' => \'2\',
            \'revision_id\' => \'2\',
          ),
          array(
            \'value\' => \'3\',
            \'revision_id\' => \'3\',
          ),
        ),
      ),
      \'field_email\' => array(
        \'und\' => array(
          array(
            \'email\' => \'michael.olugbile@gmail.com\',
          ),
        ),
      ),
      \'field_facebook_page\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Michael Opeyemi Olugbile\',
            \'format\' => NULL,
            \'safe_value\' => \'Michael Opeyemi Olugbile\',
          ),
        ),
      ),
      \'field_first_name\' => array(
        \'und\' => array(
          array(
            \'value\' => \'MICHAEL\',
            \'format\' => NULL,
            \'safe_value\' => \'MICHAEL\',
          ),
        ),
      ),
      \'field_instagram_handle\' => array(
        \'und\' => array(
          array(
            \'value\' => \'drmichaelolugbi\',
            \'format\' => NULL,
            \'safe_value\' => \'drmichaelolugbi\',
          ),
        ),
      ),
      \'field_last_name\' => array(
        \'und\' => array(
          array(
            \'value\' => \'OLUGBILE\',
            \'format\' => NULL,
            \'safe_value\' => \'OLUGBILE\',
          ),
        ),
      ),
      \'field_linkedin_page\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Dr Michael Olugbile, MD, MPH\',
            \'format\' => NULL,
            \'safe_value\' => \'Dr Michael Olugbile, MD, MPH\',
          ),
        ),
      ),
      \'field_manifesto\' => array(),
      \'field_middle_name\' => array(
        \'und\' => array(
          array(
            \'value\' => \'OPEYEMI\',
            \'format\' => NULL,
            \'safe_value\' => \'OPEYEMI\',
          ),
        ),
      ),
      \'field_personal_title\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Dr\',
          ),
        ),
      ),
      \'field_phone\' => array(
        \'und\' => array(
          array(
            \'value\' => \'08053573637\',
            \'format\' => NULL,
            \'safe_value\' => \'08053573637\',
          ),
        ),
      ),
      \'field_political_party\' => array(
        \'und\' => array(
          array(
            \'tid\' => \'2886\',
          ),
        ),
      ),
      \'field_position_running_for\' => array(
        \'und\' => array(
          array(
            \'tid\' => \'1574\',
          ),
        ),
      ),
      \'field_profile_image\' => array(
        \'und\' => array(
          array(
            \'fid\' => \'85\',
            \'uid\' => \'1\',
            \'filename\' => \'DMO.JPG\',
            \'uri\' => \'public://DMO_0.JPG\',
            \'filemime\' => \'image/jpeg\',
            \'filesize\' => \'3116655\',
            \'status\' => \'1\',
            \'timestamp\' => \'1529933779\',
            \'type\' => \'image\',
            \'uuid\' => \'95a90ce6-a5c1-4429-91b3-fb5e4cf6f69d\',
            \'field_file_image_alt_text\' => array(),
            \'field_file_image_title_text\' => array(),
            \'rdf_mapping\' => array(),
            \'metadata\' => array(
              \'height\' => 5333,
              \'width\' => 4000,
            ),
            \'height\' => \'5333\',
            \'width\' => \'4000\',
            \'alt\' => \'\',
            \'title\' => \'\',
          ),
        ),
      ),
      \'field_resume_cv\' => array(
        \'und\' => array(
          array(
            \'fid\' => \'84\',
            \'uid\' => \'1\',
            \'filename\' => \'DR MICHAEL OLUGBILE MD,MPH_2019.docx\',
            \'uri\' => \'public://DR MICHAEL OLUGBILE MD,MPH_2019_0.docx\',
            \'filemime\' => \'application/vnd.openxmlformats-officedocument.wordprocessingml.document\',
            \'filesize\' => \'42188\',
            \'status\' => \'1\',
            \'timestamp\' => \'1529933779\',
            \'type\' => \'document\',
            \'uuid\' => \'277dadf4-731c-4af5-8f7f-7bbfbc80260c\',
            \'rdf_mapping\' => array(),
            \'metadata\' => array(),
            \'display\' => \'1\',
            \'description\' => \'\',
          ),
        ),
      ),
      \'field_twitter_handle\' => array(
        \'und\' => array(
          array(
            \'value\' => \'@DrOlugbile\',
            \'format\' => NULL,
            \'safe_value\' => \'@DrOlugbile\',
          ),
        ),
      ),
      \'field_website\' => array(),
      \'files\' => array(),
      \'language\' => \'und\',
      \'last_comment_name\' => NULL,
      \'last_comment_timestamp\' => NULL,
      \'last_comment_uid\' => \'1\',
      \'log\' => \'\',
      \'menu\' => NULL,
      \'name\' => \'campaign\',
      \'nid\' => NULL,
      \'node_export_drupal_version\' => \'7\',
      \'path\' => NULL,
      \'picture\' => \'0\',
      \'promote\' => \'0\',
      \'rdf_mapping\' => array(
        \'rdftype\' => array(
          \'sioc:Item\',
          \'foaf:Document\',
        ),
        \'title\' => array(
          \'predicates\' => array(
            \'dc:title\',
          ),
        ),
        \'created\' => array(
          \'predicates\' => array(
            \'dc:date\',
            \'dc:created\',
          ),
          \'datatype\' => \'xsd:dateTime\',
          \'callback\' => \'date_iso8601\',
        ),
        \'changed\' => array(
          \'predicates\' => array(
            \'dc:modified\',
          ),
          \'datatype\' => \'xsd:dateTime\',
          \'callback\' => \'date_iso8601\',
        ),
        \'body\' => array(
          \'predicates\' => array(
            \'content:encoded\',
          ),
        ),
        \'uid\' => array(
          \'predicates\' => array(
            \'sioc:has_creator\',
          ),
          \'type\' => \'rel\',
        ),
        \'name\' => array(
          \'predicates\' => array(
            \'foaf:name\',
          ),
        ),
        \'comment_count\' => array(
          \'predicates\' => array(
            \'sioc:num_replies\',
          ),
          \'datatype\' => \'xsd:integer\',
        ),
        \'last_activity\' => array(
          \'predicates\' => array(
            \'sioc:last_activity_date\',
          ),
          \'datatype\' => \'xsd:dateTime\',
          \'callback\' => \'date_iso8601\',
        ),
      ),
      \'revision_timestamp\' => NULL,
      \'revision_uid\' => \'1\',
      \'status\' => \'0\',
      \'sticky\' => \'0\',
      \'title\' => \'Dr MICHAEL OLUGBILE for Odo-Otin/Ifelodun/Boripe, Osun, House of Representatives\',
      \'tnid\' => \'0\',
      \'translate\' => \'0\',
      \'type\' => \'campaign\',
      \'uid\' => \'1\',
      \'uuid\' => \'ed7fcdbc-70e8-4b63-8699-6c809b6d986e\',
      \'vid\' => NULL,
      \'vuuid\' => \'7dd88235-22bc-4ec7-bcb6-7e9103c4e8c1\',
    ),
)',
);
  return $node_export;
}
