<?php

/**
 * Implements hook_help().
 */
function paystack_donate_help($path, $arg) {
  switch ($path) {
    case 'admin/config/user-interface/paystack-donate':
      return '<p>' . t('Set your API parameters, default amount and your button title.') . '</p>';
  }
}

/**
 * Implements hook_permission().
 */
function paystack_donate_permission() {
  return array(
    'administer paystack_donate' => array(
      'title' => t('Administer Paystack Module'),
      'description' => t('Administer the Paystack Donate module'),
    )
  );
}

/**
 * Implements hook_menu().
 *
 * Here we set up the URLs (menu entries) for the
 * form examples. Note that most of the menu items
 * have page callbacks and page arguments set, with
 * page arguments set to be functions in external files.
 */
function paystack_donate_menu() {
  $items[variable_get('paystack_donate_link', 'donate')] = array(
    'title' => 'Donate',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('paystack_donate_form'),
    'description' => 'Donate Form',
    'file' => 'paystack_donate.inc',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  
  $items['admin/config/user-interface/paystack-donate'] = array(
    'title' => 'Paystack Donate Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('paystack_donate_admin'),
    'description' => 'Donate Form',
    'file' => 'paystack_donate.admin.inc',
    'access arguments' => array('administer paystack_donate'),
  );

  return $items;
}
